#!/usr/bin/env python3
"""Zero-trust microsegmentation policy compiler.

This script compiles a per-tier policy dict (the Policy Decision Point)
into one nftables script per host (the Policy Enforcement Point). The
shape mirrors what enterprise tools emit:

  * Calico's CalicoCtl renders to iptables / eBPF maps.
  * Cilium's CiliumNetworkPolicy renders to a TC / XDP datapath.
  * OPA's Rego renders to a sidecar-decision API.

Here the policy is plain Python (no DSL overhead, easy to sign and
review), and the output is nftables (one file per host, ready to push
with `nft -f`).

The compiled chains enforce:
  * default drop with logging
  * loopback allow
  * established/related allow (stateful conntrack)
  * per-flow allow rules from the policy
  * rate-limited SSH where the policy says
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

TIERS: dict[str, dict] = {
    "dmz":  {"subnet": "10.40.10.0/24", "hosts": {"edge": "10.40.10.1", "app": "10.40.10.2"}},
    "app":  {"subnet": "10.40.20.0/24", "hosts": {"app": "10.40.20.1"}},
    "data": {"subnet": "10.40.50.0/24", "hosts": {"db":  "10.40.50.10"}},
    "mgmt": {"subnet": "10.40.99.0/24", "hosts": {"mgmt":"10.40.99.5", "db":"10.40.99.10"}},
}

ALLOW: list[tuple[str, str, str, str, str, int]] = [
    ("dmz",  "app",  "10.40.10.0/24", "10.40.20.0/24", "tcp", 443),
    ("app",  "data", "10.40.20.0/24", "10.40.50.0/24", "tcp", 5432),
    ("mgmt", "data", "10.40.99.0/24", "10.40.50.0/24", "tcp", 22),
    ("mgmt", "dmz",  "10.40.99.0/24", "10.40.10.0/24", "tcp", 22),
]

RATE_LIMITED_SSH: set[tuple[str, str, int]] = {
    ("mgmt", "data", 22),
}


@dataclass(frozen=True)
class CompiledRule:
    src_cidr: str
    dst_cidr: str
    proto: str
    dport: int
    log_prefix: str
    rate_limited: bool


def compile_rules_for_host(host: str, host_ip: str) -> list[CompiledRule]:
    rules: list[CompiledRule] = []
    for src_tier, dst_tier, src_cidr, dst_cidr, proto, dport in ALLOW:
        if host_ip in TIERS[dst_tier]["hosts"].values():
            prefix = f"nft-drop tier={dst_tier} peer={host_ip} proto={proto} dport={dport}"
            rate_limited = (src_tier, dst_tier, dport) in RATE_LIMITED_SSH
            rules.append(
                CompiledRule(
                    src_cidr=src_cidr,
                    dst_cidr=dst_cidr,
                    proto=proto,
                    dport=dport,
                    log_prefix=prefix,
                    rate_limited=rate_limited,
                )
            )
    return rules


def collect_hosts() -> list[tuple[str, str, list[str]]]:
    hosts: dict[str, dict[str, object]] = {}
    for tier, info in TIERS.items():
        for host, ip in info["hosts"].items():
            hosts.setdefault(host, {"ip": ip, "tiers": []})
            hosts[host]["tiers"].append(tier)
    return [(h, str(v["ip"]), list(v["tiers"])) for h, v in hosts.items()]


def render_nft(host: str, host_ip: str, tiers: list[str]) -> str:
    rules: list[CompiledRule] = []
    for tier in tiers:
        for r in compile_rules_for_host(host, host_ip):
            rules.append(r)
    deduped: list[CompiledRule] = []
    seen: set[tuple[str, str, str, int, bool]] = set()
    for r in rules:
        key = (r.src_cidr, r.dst_cidr, r.proto, r.dport, r.rate_limited)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(r)

    lines: list[str] = []
    lines.append("#!/usr/sbin/nft -f")
    lines.append(f"# Auto-generated by main.py for host={host} tiers={','.join(tiers)}")
    lines.append("# Zero-trust per-host policy: default deny, explicit allow.")
    lines.append("")
    lines.append("table inet zt_filter {")
    lines.append("    set rfc1918 {")
    lines.append("        type ipv4_addr")
    lines.append("        flags interval")
    lines.append("        elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }")
    lines.append("    }")
    lines.append("")
    lines.append("    chain input {")
    lines.append("        type filter hook input priority 0; policy drop;")
    lines.append("        ct state invalid drop comment \"drop bogus\"")
    lines.append("        ct state { established, related } accept comment \"stateful\"")
    lines.append("        iif lo accept comment \"loopback\"")
    lines.append(f"        ip saddr {host_ip} accept comment \"self-traffic\"")
    for r in deduped:
        lines.append(f"        ip saddr {r.src_cidr} ip daddr {r.dst_cidr} {r.proto} dport {r.dport}")
        if r.rate_limited:
            lines.append("        meter ssh_rate { rate 3/minute burst 5 packets } accept")
        else:
            lines.append(f"        log prefix \"{r.log_prefix}\" accept")
    lines.append(f"        log prefix \"nft-drop tier={tiers[0]} default-deny\" drop")
    lines.append("    }")
    lines.append("")
    lines.append("    chain forward {")
    lines.append("        type filter hook forward priority 0; policy drop;")
    lines.append("        ct state { established, related } accept")
    for r in deduped:
        lines.append(f"        ip saddr {r.src_cidr} ip daddr {r.dst_cidr} {r.proto} dport {r.dport} accept")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    print("=" * 64)
    print("ZERO-TRUST POLICY COMPILER -- generating nftables scripts")
    print("=" * 64)
    out_dir = Path("/tmp")
    for host, ip, tiers in collect_hosts():
        script = render_nft(host, ip, tiers)
        path = out_dir / f"{host}.nft"
        path.write_text(script)
        rule_count = len(compile_rules_for_host(host, ip))
        print(f"  [{path.name}]  host={host:<7} ip={ip:<16} tiers={','.join(tiers):<10} rules={rule_count}")
    print()
    print("Apply with:")
    print("  ip netns exec edge   nft -f /tmp/edge.nft")
    print("  ip netns exec app    nft -f /tmp/app.nft")
    print("  ip netns exec db     nft -f /tmp/db.nft")
    print("  ip netns exec mgmt   nft -f /tmp/mgmt.nft")
    print()
    print("Verify with:")
    print("  ip netns exec attacker nmap -Pn -p 22,443,5432 10.40.50.10")
    print("  ip netns exec db journalctl -k --since '1 minute ago' | grep nft-drop")


if __name__ == "__main__":
    main()